esphome:
  name: logger
  friendly_name: logger

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "Vhry52t8l3JJCInErPXCNDkohD9EnDgwwizROZzTSM4="
  reboot_timeout: 0s
ota:
  - platform: esphome
    password: "12345678"


wifi:
  networks:
    - ssid: Mini_Alejandria
      password: Qwert54321
      priority: 5    # Menos prioridad
  reboot_timeout: 0s  # Desactiva el reinicio (o usa un valor mayor, ej. 1h)
  # Si no encuentra ninguna de las redes anteriores,
  # crea su propio AP (útil para emergencias).
 
  ap:
    ssid: "logger"
    password: "12345678"

web_server: 
  port: 80
  ota: true
  local: true



captive_portal:

    
