name: Build ESPHome firmware

on:
  push:
    paths:
      - '**.yaml'     # solo corre cuando cambias YAMLs
  workflow_dispatch:   # permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome==2025.5.2

      - name: Compile all yaml configs
        run: |
          mkdir -p build_output
          for file in $(find . -name "*.yaml"); do
            echo "Compiling $file ..."
            esphome compile "$file"
            # mueve los .bin generados al directorio de salida
            find . -name "*.bin" -exec cp {} build_output/ \;
          done

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esphome-firmware
          path: build_output/*.bin
